project:
  type: website

website:
  title: "The Aidan Scott Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/a1dansc0tt
format:
  html:
    theme: cosmo
    css: styles.css



