project:
  type: website

website:
  title: "Aidan Scott Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://https://github.com/ETC5523-2025/assignment-3-creating-a-blog-a1dansc0tt
format:
  html:
    theme: cosmo
    css: styles.css



